sudo: required
services:
  - docker

before_install:
  - docker build -t sarvang00/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sarvang00/react-test npm test -- --coverage

after_success:
  - docker build -t sarvang00/fibocalc-client:v3 ./client
  - docker build -t sarvang00/fibocalc-nginx ./nginx
  - docker build -t sarvang00/fibocalc-server ./server
  - docker build -t sarvang00/fibocalc-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take these images and push them to dockerhub
  - docker push sarvang00/fibocalc-client
  - docker push sarvang00/fibocalc-nginx
  - docker push sarvang00/fibocalc-server
  - docker push sarvang00/fibocalc-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-south-1"
#   app: "multi-docker-fibo-calc"
#   env: "Multidockerfibocalc-env"
#   bucket_name: "elasticbeanstalk-ap-south-1-585360292342"
#   bucket_path: "multi-docker-fibo-calc"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY